blogdinossauro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), 
    path('posts/', include('posts.urls')), 
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('search/', views.search_posts, name='search'),
    path('', views.PostListView.as_view(), name='index'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:category_id>/', views.category_detail, name='categorydetail'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), 
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models

from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    img_url = models.URLField(max_length=200, null=True)
    text = models.CharField(max_length=1023)

    def __str__(self):
        return f'{self.name} ({self.date})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'img_url',
            'text',
        ]
        labels = {
            'name': 'Título',
            'img_url': 'URL da Imagem',
            'text': 'Conteúdo em Texto',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

posts/views.py
from django.views import generic
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm


class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)



class PostCreateView(generic.CreateView):
    context_object_name = 'post'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "posts/create.html"

    def get_success_url(self):
        return reverse('posts:detail', kwargs={'pk': self.object.id})
class PostUpdateView(generic.UpdateView):
    context_object_name = 'post'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "posts/update.html"

    def get_success_url(self):
        return reverse('posts:detail', kwargs={'pk': self.object.id})

class PostDeleteView(generic.DeleteView):
    model = Post
    context_object_name = 'post'
    template_name = 'posts/delete.html'
    def get_success_url(self):
        return reverse('posts:index')


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categorylist.html'

def category_detail(request, category_id):
    category = get_object_or_404(Category, pk = category_id)
    context = {'category' : category}
    return render(request, 'posts/categorydetail.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/categorydetail.html
{% extends 'base.html' %}

{% block title %}
{{category.name | safe}}
{% endblock title %}

{% block content %}
<h2>{{category.name | safe}}</h2>
<p>{{category.description | safe}}</p>
<hr>
<section>
    <article>
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.img_url }}"
                        alt="Imagem do post {{ post.name}}"></a>
                <p><b>{{ post.name | safe}}</b></p>
                <p>{{ post.text | safe}}</p>
            </div>
            {% endfor %}
        </div>
    </article>
</section>

{% endblock content %}

posts/templates/posts/categorylist.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'posts:categorydetail' category.id %}"><h2>{{category.name}}</h2></a>
            <p>{{category.description}}</p>
        </header>
    </article>
    {% endfor %}
</section>


{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Post {{ post.name }} ({{ post.date }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Criar Nova Postagem</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o filme "{{ post.name }} ({{ post.date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.date }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ post.name | safe}} ({{ post.date | date}})</h2>

<section class="dados-de-filme">
    <img src="{{ post.img_url }}" alt="Imagem do filme {{ post.name}}">
    <ul>
        <li>Nome: {{ post.name | safe }}</li>
        <li>Data da Postagem: {{ post.date | date }} </li>
        <li>Conteúdo: {{ post.text | safe}}</li>
        {% if post.category_set.all %}
            <li><b>Categorias:</b></li>
                <ul>
                {% for category in post.category_set.all %} 
                    <li> <a href="{% url 'posts:categorydetail' category.id %}"> {{ category.name }} </a></li>
                {% endfor %} 
                </ul>
        {% endif %}

        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all|dictsortreversed:"date" %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                        "{{ comment.date | date }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não há comentários neste post.</p>
        {% endif %}
    </ul>
    <hr>
    <a href="{% url 'posts:comment' post.pk %}"><button>Comente!</button></a>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Post</a></p>
    <p>Quer compartilhar algo interessante? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.img_url }}"
                alt=" {{ post.name}}"></a> 
        <p>{{ post.name | safe }}</p>
        <p>({{ post.date | date }})</p>
        <p>{{post.text | safe }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Nome</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Nome:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.img_url }}" alt="Imagem para o post {{ post.name}}">
        <p>{{ post.name | safe}} ({{ post.date | date})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Postagem {{ post.name }}({{ post.date}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Blog Sobre Dinossauros
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>BSD</p>
        </a>     
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Postagens</a></li> 
                <li><a href="{% url 'posts:categories' %}">Categorias</a></li> 
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>PMR 3304</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Blog sobre Dinossauros</i></h1>
<p>A Página para postar imagens, textos e notícias sobre dinossauros. E paleontologia no geral.</p>
{% endblock content %}